projects:
  spring-boot:
    testModulePatterns:
      - "*-test"
      - "*-tests"
      - "*-test-autoconfigure"
      - "*-test-support"
    integrationTestSourceRoots:
      - src/integrationTest/java
      - src/it/java
